### ISSUE TITLE
显示检查配置文件是否合法

### ISSUE THREAD

**Issue by Onlyn1ght** [gakkiyomi/pwl-chat-python#2]
![image](https://user-images.githubusercontent.com/91249019/186297986-4f01ae90-2910-4121-9481-ba14f4594816.png)
`config.read('./config.ini', encoding='utf-8')`改成`config.read('./config.ini', encoding='utf-8-sig')`
解决这个问题

**Comment by gakkiyomi** [comment]
请问在什么情况下会出现编码问题

**Comment by gakkiyomi** [comment]
目前暂未复现 在macos与  linux  上正常
