### ISSUE TITLE
弄一个自动发猜拳红包的机器人怎么样

### ISSUE THREAD

**Issue by TwoCarPongPong** [gakkiyomi/pwl-chat-python#60]
可以设置时间间隔 大小 然后随机出拳

**Comment by gakkiyomi** [comment]
> 可以设置时间间隔 大小 然后随机出拳

机器人需要报备，而且鱼排30s只能发一个猜拳，加上会降低别人的体验

**Comment by TwoCarPongPong** [comment]
🤔

**Comment by TwoCarPongPong** [comment]
能给一个编译命令吗&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月2日(星期四) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gakkiyomi/pwl-chat-python] 弄一个自动发猜拳红包的机器人怎么样 (Issue #60)





  
可以设置时间间隔 大小 然后随机出拳
  
机器人需要报备，而且鱼排30s只能发一个猜拳，加上会降低别人的体验

**Comment by gakkiyomi** [comment]
> 能给一个编译命令吗&nbsp; &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月2日(星期四) 下午3:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [gakkiyomi/pwl-chat-python] 弄一个自动发猜拳红包的机器人怎么样 (Issue #60) 可以设置时间间隔 大小 然后随机出拳 机器人需要报备，而且鱼排30s只能发一个猜拳，加上会降低别人的体验 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

pip install -r requirements.txt
python core.py
